name: androidBuild
on:
  pull_request:
    branches: [dev]
  push:
    branches:
      - 'release-*'

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: budget-debug-${{ env.COMMIT_HASH }}.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk